kind: Service

apiVersion: v1

metadata:

  name: train-schedule-service-canary

spec:

  type: ClusterIP

  selector:

    app: train-schedule

    track: canary

  ports:

  - port: 8080

    targetPort: 8080



---


apiVersion: apps/v1

kind: Deployment

metadata:

  name: train-schedule-deployment-canary

  labels:

    app: train-schedule

spec:

  replicas: 1

  selector:

    matchLabels:

      app: train-schedule

      track: canary

  template:

    metadata:

      labels:

        app: train-schedule

        track: canary

    spec:

      containers:

      - name: train-schedule

        image: addalin/trainschedule:latest

        ports:

        - containerPort: 8080


