kind: Service

apiVersion: v1

metadata:

  name: train-schedule-service

spec:

  type: ClusterIP

  selector:

    app: train-schedule

  ports:

  - port: 8080

    targetPort: 8080



---


apiVersion: apps/v1

kind: Deployment

metadata:

  name: train-schedule-deployment

  labels:

    app: train-schedule

spec:

  replicas: 2

  selector:

    matchLabels:

      app: train-schedule

      track: stable

  template:

    metadata:

      labels:

        app: train-schedule

        track: stable

    spec:

      containers:

      - name: train-schedule

        image: addalin/trainschedule:latest

        ports:

        - containerPort: 8080


